PREFIX wp: <http://vocabularies.wikipathways.org/wp#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?pw (STR(?titleLit) AS ?title)
FROM <http://plantmetwiki.bioinformatics.nl/>
WHERE {
  ?pw wp:organismName "Solanum tuberosum" ;
      dc:title ?titleLit .
}
ORDER BY ?title
LIMIT 200