# Show all species (with NCBI taxon IDs and labels) present in a given pathway.
# Species are identified from DataNode-level annotations in the taxonomy-extra graph.
# Replace pmw:PC159 with the pathway ID of interest.
PREFIX wp:      <http://vocabularies.wikipathways.org/wp#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc:      <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ncbi:    <http://purl.obolibrary.org/obo/NCBITaxon_>
PREFIX pmw:     <http://rdf-plantmetwiki.bioinformatics.nl/pathways/>

SELECT DISTINCT ?taxonID ?species ?title
WHERE {
  # Find the pathway
  GRAPH <http://rdf-plantmetwiki.bioinformatics.nl/graph/pathways> {
    ?pw dc:identifier pmw:PC159 ;  # change pathway ID here
        dc:title ?title .
    ?dataNode dcterms:isPartOf ?pw .
  }
  # Get species annotation on DataNodes in this pathway
  GRAPH <http://rdf-plantmetwiki.bioinformatics.nl/graph/gpml-taxonomy-extra> {
    ?dataNode wp:organism ?taxonID .
    FILTER(?taxonID != ncbi:33090)  # exclude pathway-level Viridiplantae
  }
  # Resolve taxon label
  GRAPH <http://rdf-plantmetwiki.bioinformatics.nl/graph/ncbitaxon> {
    ?taxonID rdfs:label ?species .
  }
}
ORDER BY ?species
